
markdown: redcarpet
baseurl: "/plz"
permalink: none
pygments: true
redcarpet:
  extensions:
    - hard_wrap
    - no_intra_emphasis
    - autolink
    - strikethrough
    - fenced_code_blocks

toc:
  - title: "How it works"
    link: "how-it-works"
  - title: "Writing tasks"
    link: "writing-tasks"
    chapters:
      - title: "Watching files"
        link: "watching-files"
      - title: "Run function"
        link: "run"
      - title: "Dependencies"
        link: "dependencies"
      - title: "Before and after tasks"
        link: "before-and-after"
