
markdown: redcarpet
baseurl: "/plz"
permalink: none
pygments: true
redcarpet:
  extensions:
    - hard_wrap
    - no_intra_emphasis
    - autolink
    - strikethrough
    - fenced_code_blocks

toc:
  - title: "What is it?"
    link: "what-is-it"
    chapters:
      - title: "Manifesto"
        link: "manifesto"
      - title: "Example"
        link: "example"
  - title: "How it works"
    link: "how-it-works"
  - title: "Basic tasks"
    link: "basic-tasks"
    chapters:
      - title: "clean"
        link: "clean"
      - title: "distclean"
        link: "distclean"
      - title: "build"
        link: "build"
      - title: "test"
        link: "test"
      - title: "install"
        link: "install"
  - title: "Writing tasks"
    link: "writing-tasks"
    chapters:
      - title: "Watching files"
        link: "watching-files"
      - title: "Run function"
        link: "run"
      - title: "Dependencies"
        link: "dependencies"
      - title: "Before and after tasks"
        link: "before-and-after"
  - title: "Available functions"
    link: "available-functions"
    chapters:
      - title: "Basic globals"
        link: "basic-globals"
      - title: "Logging"
        link: "logging"
      - title: "Shell commands"
        link: "shell-commands"
      - title: "Exec"
        link: "exec"
      - title: "Settings"
        link: "settings"
      - title: "Project info"
        link: "project-info"
      - title: "Configuration"
        link: "configuration"
      - title: "Tasks"
        link: "tasks"
  - title: "Plugins"
    link: "plugins"
    chapters:
      - title: "Mocha"
        link: "mocha"
      - title: "Coffee-script"
        link: "coffee-script"
